#+TITLE: Datomic Table Structure
* SQL

	SQL is built on relational algebra.

	A table is a function from the primary key into the space defined by the
	columns.

	Example:

	| ID | Size | Shape    | Colour        | Description        |
	|----+------+----------+---------------+--------------------|
	|  1 |    4 | square   | (0, 70, 255)  | "Kind of blockish" |
	|  2 |    3 | oblong   | (255, 0, 255) | "Not quite round"  |
	|  3 |    7 | triangle | (0, 0, 0)     | "Pointy!"          |
	|    |      |          |               |                    |
	...

	This table maps IDs into the space of (size, shape, colour, description).

	At the end of the day, it's just a function!

* Datomic Tuple
** Facts
	 Datomic is also built on relational algebra.

	 But the kinds of functions you can define is much more restricted.

	 Datomic builds data from facts.

	 A fact is a single, atomic piece of information asserted at a particular
	 time.

	 E.g.: My phone number is 555-1234 as of now.
** EAV
	 In Datomic, all functions have "simple" ranges.

	 In other words, tables only have one non-id column.

	 | ID | Size |
	 |----+------|
	 |  1 |    4 |
	 |  2 |    3 |
	 |  3 |    7 |

	 | ID | Shape    |
	 |----+----------|
	 |  1 | square   |
	 |  2 | oblong   |
	 |  3 | triangle |

	 This is sometimes called a schema in Sixth Normal Form.

** Datoms
	 Atomic Facts (data) are called datoms in Datomic.

	 Datoms are tuples of the type [E A V Tx Op] Where:

	 E: an entity ID (just like a primary key in sql).

	 A: an attribute (name of a column).

	 V: the value of the attribute for this entity.

	 Tx: the transaction during which this datom was added to the DB.

	 Op: is this an assertion that the fact is true, or false?

** EAVT
	 So we can see that our table analogy was a slight lie.

	 Tables in Datomic only have one column *that you can control*.

	 They really look like this:

	 | ID | Size | Tx | Op   |
	 |----+------+----+------|
	 |  1 |    4 |  1 | True |
	 |  2 |    3 |  2 | True |
	 |  3 |    7 |  3 | True |
** Schemata
** Indicies
